language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="8d494bbf-72b8-44c6-9d72-003c3b612bfa"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -egorsarantsev4565@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always