insert into category(name) values('CAT_1');
insert into category(name) values('CAT_2');
insert into category(name) values('CAT_3');
insert into state(name) values('ST_1');
insert into state(name) values('ST_2');
insert into state(name) values('ST_3');
insert into role(name) values('RO_1');
insert into role(name) values('RO_2');
insert into role(name) values('RO_3');
insert into rules(name) values('RU_1');
insert into rules(name) values('RU_2');
insert into rules(name) values('RU_3');
insert into role_rules(role_id, rules_id) values (1, 2);
insert into role_rules(role_id, rules_id) values (2, 3);
insert into role_rules(role_id, rules_id) values (3, 1);
insert into users(name, role_id) values('U_1',1);
insert into users(name, role_id) values('U_2',2);
insert into users(name, role_id) values('U_3',3);
insert into item(name, users_id, category_id, state_id) values ('I_1', 1, 2, 3);
insert into item(name, users_id, category_id, state_id) values ('I_2', 2, 1, 2);
insert into item(name, users_id, category_id, state_id) values ('I_3', 3, 3, 1);
insert into comments(name, item_id) values ('C_1', 2);
insert into comments(name, item_id) values ('C_2', 3);
insert into comments(name, item_id) values ('C_3', 1);
insert into attachs(name, item_id) values ('A_1', 3);
insert into attachs(name, item_id) values ('A_2', 1);
insert into attachs(name, item_id) values ('A_3', 2);